# Generated by Django 4.0.6 on 2022-07-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('choice1', models.CharField(max_length=40)),
                ('choice2', models.CharField(max_length=40)),
                ('choice3', models.CharField(max_length=40)),
                ('choice1_count', models.IntegerField(default=0)),
                ('choice2_count', models.IntegerField(default=0)),
                ('choice3_count', models.IntegerField(default=0)),
            ],
        ),
    ]
