# Generated by Django 4.0.6 on 2022-07-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='choice4',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='choice4_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='poll',
            name='choice1',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='choice2',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='poll',
            name='choice3',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
