# Generated by Django 4.0.6 on 2022-07-06 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poll', '0006_remove_profile_user_profile_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
